version: '3'

services:
  memoryvault.logger.si:
    image: memoryvault.logger.si
    build:
      context: .
      dockerfile: ./MemoryVault.Logger.SI/Dockerfile
    ports:
      - 8201:80
    links:
      - mongodb_log
    depends_on:
      - mongodb_log
    networks:
      - frontend
      - backend

  mongodb_log:
    image: mongo:latest
    container_name: mongodb_log
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - C:/DOCKER_DATA/mongodb_log/data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - backend

networks:
  frontend:
  backend: